apiVersion: apps/v1
kind: Deployment
metadata:
  name: karka-english
  namespace: karka-english
  labels:
    app: karka-english
spec:
  replicas: 2
  selector:
    matchLabels:
      app: karka-english
  template:
    metadata:
      labels:
        app: karka-english
    spec:
      containers:
        - name: karka-english
          image: sudeep18k/karka-english:v1
          ports:
            - containerPort: 4173
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: karka-secret
                  key: GROQ_API_KEY
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 4173
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4173
            initialDelaySeconds: 10
            periodSeconds: 30
