apiVersion: v1
kind: Service
metadata:
  name: karka-english
  namespace: karka-english
spec:
  type: LoadBalancer
  selector:
    app: karka-english
  ports:
    - port: 80
      targetPort: 4173
      protocol: TCP
