export interface WordPair {
  english: string;
  kannada: string;
  category: string;
}

export const vocabularyData: WordPair[] = [
  // Greetings
  { english: "Hello", kannada: "ನಮಸ್ಕಾರ (Namaskara)", category: "Greetings" },
  { english: "Good morning", kannada: "ಶುಭೋದಯ (Shubhodaya)", category: "Greetings" },
  { english: "Good night", kannada: "ಶುಭ ರಾತ್ರಿ (Shubha ratri)", category: "Greetings" },
  { english: "Thank you", kannada: "ಧನ್ಯವಾದಗಳು (Dhanyavadagalu)", category: "Greetings" },
  { english: "Welcome", kannada: "ಸ್ವಾಗತ (Swagata)", category: "Greetings" },
  { english: "Sorry", kannada: "ಕ್ಷಮಿಸಿ (Kshamisi)", category: "Greetings" },
  { english: "How are you?", kannada: "ಹೇಗಿದ್ದೀರಾ? (Hegiddira?)", category: "Greetings" },
  { english: "I am fine", kannada: "ನಾನು ಆರಾಮವಾಗಿದ್ದೇನೆ (Nanu aramavagiddene)", category: "Greetings" },
  { english: "Goodbye", kannada: "ಹೋಗಿ ಬರುತ್ತೇನೆ (Hogi baruttene)", category: "Greetings" },

  // School
  { english: "Teacher", kannada: "ಶಿಕ್ಷಕ (Shikshaka)", category: "School" },
  { english: "Student", kannada: "ವಿದ್ಯಾರ್ಥಿ (Vidyarthi)", category: "School" },
  { english: "Book", kannada: "ಪುಸ್ತಕ (Pustaka)", category: "School" },
  { english: "Pen", kannada: "ಲೇಖನಿ (Lekhani)", category: "School" },
  { english: "School", kannada: "ಶಾಲೆ (Shaale)", category: "School" },
  { english: "Classroom", kannada: "ತರಗತಿ (Taragati)", category: "School" },
  { english: "Homework", kannada: "ಮನೆಗೆಲಸ (Manegelasa)", category: "School" },
  { english: "Exam", kannada: "ಪರೀಕ್ಷೆ (Parikshe)", category: "School" },
  { english: "Library", kannada: "ಗ್ರಂಥಾಲಯ (Granthalaya)", category: "School" },
  { english: "Pencil", kannada: "ಸೀಸದ ಕಡ್ಡಿ (Sisada kaddi)", category: "School" },

  // Family
  { english: "Father", kannada: "ತಂದೆ (Tande)", category: "Family" },
  { english: "Mother", kannada: "ತಾಯಿ (Tayi)", category: "Family" },
  { english: "Brother", kannada: "ಸಹೋದರ (Sahodara)", category: "Family" },
  { english: "Sister", kannada: "ಸಹೋದರಿ (Sahodari)", category: "Family" },
  { english: "Grandfather", kannada: "ತಾತ (Tata)", category: "Family" },
  { english: "Grandmother", kannada: "ಅಜ್ಜಿ (Ajji)", category: "Family" },
  { english: "Son", kannada: "ಮಗ (Maga)", category: "Family" },
  { english: "Daughter", kannada: "ಮಗಳು (Magalu)", category: "Family" },
  { english: "Uncle", kannada: "ಚಿಕ್ಕಪ್ಪ/ಮಾವ (Chikkappa/Mava)", category: "Family" },
  { english: "Aunt", kannada: "ಚಿಕ್ಕಮ್ಮ/ಅತ್ತೆ (Chikkamma/Atte)", category: "Family" },

  // Food
  { english: "Water", kannada: "ನೀರು (Neeru)", category: "Food" },
  { english: "Food", kannada: "ಆಹಾರ (Ahara)", category: "Food" },
  { english: "Rice", kannada: "ಅನ್ನ (Anna)", category: "Food" },
  { english: "Milk", kannada: "ಹಾಲು (Haalu)", category: "Food" },
  { english: "Fruit", kannada: "ಹಣ್ಣು (Hannu)", category: "Food" },
  { english: "Vegetable", kannada: "ತರಕಾರಿ (Tarakari)", category: "Food" },
  { english: "Sugar", kannada: "ಸಕ್ಕರೆ (Sakkare)", category: "Food" },
  { english: "Salt", kannada: "ಉಪ್ಪು (Uppu)", category: "Food" },
  { english: "Bread", kannada: "ರೊಟ್ಟಿ (Rotti)", category: "Food" },
  { english: "Tea", kannada: "ಚಹಾ (Chaha)", category: "Food" },

  // Colors
  { english: "Red", kannada: "ಕೆಂಪು (Kempu)", category: "Colors" },
  { english: "Blue", kannada: "ನೀಲಿ (Neeli)", category: "Colors" },
  { english: "Green", kannada: "ಹಸಿರು (Hasiru)", category: "Colors" },
  { english: "Yellow", kannada: "ಹಳದಿ (Haladi)", category: "Colors" },
  { english: "Black", kannada: "ಕಪ್ಪು (Kappu)", category: "Colors" },
  { english: "White", kannada: "ಬಿಳಿ (Bili)", category: "Colors" },
  { english: "Orange", kannada: "ಕಿತ್ತಳೆ (Kittale)", category: "Colors" },
  { english: "Pink", kannada: "ಗುಲಾಬಿ (Gulabi)", category: "Colors" },
  { english: "Purple", kannada: "ನೇರಳೆ (Nerale)", category: "Colors" },
  { english: "Brown", kannada: "ಕಂದು (Kandu)", category: "Colors" },

  // Emotions
  { english: "Happy", kannada: "ಸಂತೋಷ (Santosha)", category: "Emotions" },
  { english: "Sad", kannada: "ದುಃಖ (Dukha)", category: "Emotions" },
  { english: "Angry", kannada: "ಕೋಪ (Kopa)", category: "Emotions" },
  { english: "Fear", kannada: "ಭಯ (Bhaya)", category: "Emotions" },
  { english: "Surprise", kannada: "ಆಶ್ಚರ್ಯ (Ashcharya)", category: "Emotions" },
  { english: "Love", kannada: "ಪ್ರೀತಿ (Preeti)", category: "Emotions" },
  { english: "Hungry", kannada: "ಹಸಿವು (Hasivu)", category: "Emotions" },
  { english: "Thirsty", kannada: "ಬಾಯಾರಿಕೆ (Bayarike)", category: "Emotions" },
  { english: "Tired", kannada: "ದಣಿವು (Danivu)", category: "Emotions" },
  { english: "Excited", kannada: "ಉತ್ಸಾಹ (Utsaha)", category: "Emotions" },

  // Animals
  { english: "Dog", kannada: "ನಾಯಿ (Nayi)", category: "Animals" },
  { english: "Cat", kannada: "ಬೆಕ್ಕು (Bekku)", category: "Animals" },
  { english: "Cow", kannada: "ಹಸು (Hasu)", category: "Animals" },
  { english: "Elephant", kannada: "ಆನೆ (Aane)", category: "Animals" },
  { english: "Lion", kannada: "ಸಿಂಹ (Simha)", category: "Animals" },
  { english: "Tiger", kannada: "ಹುಲಿ (Huli)", category: "Animals" },
  { english: "Bird", kannada: "ಪಕ್ಷಿ (Pakshi)", category: "Animals" },
  { english: "Fish", kannada: "ಮೀನು (Meenu)", category: "Animals" },
  { english: "Snake", kannada: "ಹಾವು (Haavu)", category: "Animals" },
  { english: "Monkey", kannada: "ಕೋತಿ (Koti)", category: "Animals" },

  // Numbers
  { english: "One", kannada: "ಒಂದು (Ondu)", category: "Numbers" },
  { english: "Two", kannada: "ಎರಡು (Eradu)", category: "Numbers" },
  { english: "Three", kannada: "ಮೂರು (Muru)", category: "Numbers" },
  { english: "Four", kannada: "ನಾಲ್ಕು (Nalku)", category: "Numbers" },
  { english: "Five", kannada: "ಐದು (Aidu)", category: "Numbers" },
  { english: "Six", kannada: "ಆರು (Aaru)", category: "Numbers" },
  { english: "Seven", kannada: "ಏಳು (Elu)", category: "Numbers" },
  { english: "Eight", kannada: "ಎಂಟು (Entu)", category: "Numbers" },
  { english: "Nine", kannada: "ಒಂಬತ್ತು (Ombattu)", category: "Numbers" },
  { english: "Ten", kannada: "ಹತ್ತು (Hattu)", category: "Numbers" },

  // Verbs
  { english: "Go", kannada: "ಹೋಗು (Hogu)", category: "Verbs" },
  { english: "Come", kannada: "ಬಾ (Ba)", category: "Verbs" },
  { english: "Eat", kannada: "ತಿನ್ನು (Tinnu)", category: "Verbs" },
  { english: "Drink", kannada: "ಕುಡಿ (Kudi)", category: "Verbs" },
  { english: "Sleep", kannada: "ಮಲಗು (Malagu)", category: "Verbs" },
  { english: "Read", kannada: "ಓದು (Odu)", category: "Verbs" },
  { english: "Write", kannada: "ಬರೆ (Bare)", category: "Verbs" },
  { english: "Speak", kannada: "ಮಾತನಾಡು (Matanadu)", category: "Verbs" },
  { english: "Run", kannada: "ಓಡು (Odu)", category: "Verbs" },
  { english: "Walk", kannada: "ನಡೆ (Nade)", category: "Verbs" },
  { english: "Sit", kannada: "ಕುಳಿತುಕೊ (Kulituko)", category: "Verbs" },
  { english: "Stand", kannada: "ನಿಂತುಕೊ (Nintuko)", category: "Verbs" },
  { english: "Play", kannada: "ಆಟವಾಡು (Atavadu)", category: "Verbs" },
  { english: "Sing", kannada: "ಹಾಡು (Hadu)", category: "Verbs" },
  { english: "Dance", kannada: "ಕುಣಿಯಿರಿ (Kuniyiri)", category: "Verbs" },
  { english: "Laugh", kannada: "ನಗು (Nagu)", category: "Verbs" },
  { english: "Cry", kannada: "ಅಳು (Alu)", category: "Verbs" },
  { english: "Work", kannada: "ಕೆಲಸ ಮಾಡು (Kelasa madu)", category: "Verbs" },
  { english: "Study", kannada: "ಅಭ್ಯಾಸ ಮಾಡು (Abhyasa madu)", category: "Verbs" },
  { english: "Learn", kannada: "ಕಲಿ (Kali)", category: "Verbs" },

  // Adding more to reach 177 or close to it as requested
  { english: "Sun", kannada: "ಸೂರ್ಯ (Surya)", category: "Nature" },
  { english: "Moon", kannada: "ಚಂದ್ರ (Chandra)", category: "Nature" },
  { english: "Star", kannada: "ನಕ್ಷತ್ರ (Nakshatra)", category: "Nature" },
  { english: "Sky", kannada: "ಆಕಾಶ (Akasha)", category: "Nature" },
  { english: "Rain", kannada: "ಮಳೆ (Male)", category: "Nature" },
  { english: "Wind", kannada: "ಗಾಳಿ (Gaali)", category: "Nature" },
  { english: "Tree", kannada: "ಮರ (Mara)", category: "Nature" },
  { english: "Flower", kannada: "ಹೂವು (Huvu)", category: "Nature" },
  { english: "River", kannada: "ನದಿ (Nadi)", category: "Nature" },
  { english: "Mountain", kannada: "ಪರ್ವತ (Parvata)", category: "Nature" },
  { english: "Earth", kannada: "ಭೂಮಿ (Bhumi)", category: "Nature" },
  { english: "Fire", kannada: "ಬೆಂಕಿ (Benki)", category: "Nature" },
  { english: "Air", kannada: "ಗಾಳಿ (Gaali)", category: "Nature" },
  { english: "Cloud", kannada: "ಮೋಡ (Moda)", category: "Nature" },
  { english: "Sea", kannada: "ಸಮುದ್ರ (Samudra)", category: "Nature" },

  { english: "House", kannada: "ಮನೆ (Mane)", category: "Home" },
  { english: "Door", kannada: "ಬಾಗಿಲು (Bagilu)", category: "Home" },
  { english: "Window", kannada: "ಕಿಟಕಿ (Kitaki)", category: "Home" },
  { english: "Room", kannada: "ಕೋಣೆ (Kone)", category: "Home" },
  { english: "Kitchen", kannada: "ಅಡುಗೆ ಮನೆ (Aduge mane)", category: "Home" },
  { english: "Bed", kannada: "ಹಾಸಿಗೆ (Hasige)", category: "Home" },
  { english: "Chair", kannada: "ಕುರ್ಚಿ (Kurchi)", category: "Home" },
  { english: "Table", kannada: "ಮೇಜು (Meju)", category: "Home" },
  { english: "Light", kannada: "ಬೆಳಕು (Belaku)", category: "Home" },
  { english: "Fan", kannada: "ಫ್ಯಾನ್ (Fan)", category: "Home" },

  { english: "Body", kannada: "ದೇಹ (Deha)", category: "Body Parts" },
  { english: "Head", kannada: "ತಲೆ (Tale)", category: "Body Parts" },
  { english: "Eye", kannada: "ಕಣ್ಣು (Kannu)", category: "Body Parts" },
  { english: "Ear", kannada: "ಕಿವಿ (Kivi)", category: "Body Parts" },
  { english: "Nose", kannada: "ಮೂಗು (Mugu)", category: "Body Parts" },
  { english: "Mouth", kannada: "ಬಾಯಿ (Bayi)", category: "Body Parts" },
  { english: "Hand", kannada: "ಕೈ (Kai)", category: "Body Parts" },
  { english: "Leg", kannada: "ಕಾಲು (Kaalu)", category: "Body Parts" },
  { english: "Face", kannada: "ಮುಖ (Mukha)", category: "Body Parts" },
  { english: "Hair", kannada: "ಕೂದಲು (Kudalu)", category: "Body Parts" },
  { english: "Tooth", kannada: "ಹಲ್ಲು (Hallu)", category: "Body Parts" },
  { english: "Tongue", kannada: "ನಾಲಿಗೆ (Nalige)", category: "Body Parts" },
  { english: "Finger", kannada: "ಬೆರಳು (Beralu)", category: "Body Parts" },
  { english: "Shoulder", kannada: "ಹೆಗಲು (Hegalu)", category: "Body Parts" },
  { english: "Stomach", kannada: "ಹೊಟ್ಟೆ (Hotte)", category: "Body Parts" },

  { english: "Time", kannada: "ಸಮಯ (Samaya)", category: "Time" },
  { english: "Day", kannada: "ದಿನ (Dina)", category: "Time" },
  { english: "Night", kannada: "ರಾತ್ರಿ (Ratri)", category: "Time" },
  { english: "Week", kannada: "ವಾರ (Vaara)", category: "Time" },
  { english: "Month", kannada: "ತಿಂಗಳು (Tingalu)", category: "Time" },
  { english: "Year", kannada: "ವರ್ಷ (Varsha)", category: "Time" },
  { english: "Today", kannada: "ಇಂದು (Indu)", category: "Time" },
  { english: "Tomorrow", kannada: "ನಾಳೆ (Naale)", category: "Time" },
  { english: "Yesterday", kannada: "ನಿನ್ನೆ (Ninne)", category: "Time" },
  { english: "Morning", kannada: "ಬೆಳಿಗ್ಗೆ (Beligge)", category: "Time" },
  { english: "Afternoon", kannada: "ಮಧ್ಯಾಹ್ನ (Madhyahna)", category: "Time" },
  { english: "Evening", kannada: "ಸಂಜೆ (Sanje)", category: "Time" },
  { english: "Hour", kannada: "ಗಂಟೆ (Gante)", category: "Time" },
  { english: "Minute", kannada: "ನಿಮಿಷ (Nimisha)", category: "Time" },
  { english: "Second", kannada: "ಸೆಕೆಂಡ್ (Second)", category: "Time" },

  { english: "City", kannada: "ನಗರ (Nagara)", category: "Places" },
  { english: "Village", kannada: "ಹಳ್ಳಿ (Halli)", category: "Places" },
  { english: "Road", kannada: "ರಸ್ತೆ (Raste)", category: "Places" },
  { english: "Shop", kannada: "ಅಂಗಡಿ (Angadi)", category: "Places" },
  { english: "Market", kannada: "ಮಾರುಕಟ್ಟೆ (Marukatte)", category: "Places" },
  { english: "Hospital", kannada: "ಆಸ್ಪತ್ರೆ (Aspatre)", category: "Places" },
  { english: "Police Station", kannada: "ಪೊಲೀಸ್ ಠಾಣೆ (Police thane)", category: "Places" },
  { english: "Park", kannada: "ಉದ್ಯಾನವನ (Udyanavana)", category: "Places" },
  { english: "Bank", kannada: "ಬ್ಯಾಂಕ್ (Bank)", category: "Places" },
  { english: "Post Office", kannada: "ಅಂಚೆ ಕಚೇರಿ (Anche kacheri)", category: "Places" },

  { english: "Clothes", kannada: "ಬಟ್ಟೆಗಳು (Battegalu)", category: "Objects" },
  { english: "Shoes", kannada: "ಬೂಟುಗಳು (Butugalu)", category: "Objects" },
  { english: "Watch", kannada: "ಗಡಿಯಾರ (Gadiyara)", category: "Objects" },
  { english: "Bag", kannada: "ಚೀಲ (Cheela)", category: "Objects" },
  { english: "Money", kannada: "ಹಣ (Hana)", category: "Objects" },
  { english: "Key", kannada: "ಕೀಲಿ (Keeli)", category: "Objects" },
  { english: "Phone", kannada: "ದೂರವಾಣಿ (Duravani)", category: "Objects" },
  { english: "Computer", kannada: "ಗಣಕಯಂತ್ರ (Ganakayantra)", category: "Objects" },
  { english: "Car", kannada: "ಕಾರು (Kaaru)", category: "Objects" },
  { english: "Bicycle", kannada: "ಸೈಕಲ್ (Cycle)", category: "Objects" },

  { english: "Big", kannada: "ದೊಡ್ಡ (Dodda)", category: "Adjectives" },
  { english: "Small", kannada: "ಸಣ್ಣ (Sanna)", category: "Adjectives" },
  { english: "Good", kannada: "ಒಳ್ಳೆಯ (Olleya)", category: "Adjectives" },
  { english: "Bad", kannada: "ಕೆಟ್ಟ (Ketta)", category: "Adjectives" },
  { english: "Hot", kannada: "ಬಿಸಿ (Bisi)", category: "Adjectives" },
  { english: "Cold", kannada: "ತಂಪು (Tampu)", category: "Adjectives" },
  { english: "New", kannada: "ಹೊಸ (Hosa)", category: "Adjectives" },
  { english: "Old", kannada: "ಹಳೆಯ (Haleya)", category: "Adjectives" },
  { english: "Fast", kannada: "ವೇಗ (Vega)", category: "Adjectives" },
  { english: "Slow", kannada: "ನಿಧಾನ (Nidhana)", category: "Adjectives" },
  { english: "Beautiful", kannada: "ಸುಂದರ (Sundara)", category: "Adjectives" },
  { english: "Ugly", kannada: "ವಿಕಾರ (Vikara)", category: "Adjectives" },
  { english: "Strong", kannada: "ಬಲಶಾಲಿ (Balashali)", category: "Adjectives" },
  { english: "Weak", kannada: "ದುರ್ಬಲ (Durbala)", category: "Adjectives" },
  { english: "Rich", kannada: "ಶ್ರೀಮಂತ (Shrimanta)", category: "Adjectives" },
  { english: "Poor", kannada: "ಬಡ (Bada)", category: "Adjectives" },
  { english: "Tall", kannada: "ಎತ್ತರ (Ettara)", category: "Adjectives" },
  { english: "Short", kannada: "ಗಿಡ್ಡ (Gidda)", category: "Adjectives" },
  { english: "Clean", kannada: "ಶುದ್ಧ (Shuddha)", category: "Adjectives" },
  { english: "Dirty", kannada: "ಗಲೀಜು (Galeeju)", category: "Adjectives" },

  { english: "Friend", kannada: "ಸ್ನೇಹಿತ (Snehita)", category: "People" },
  { english: "Enemy", kannada: "ಶತ್ರು (Shatru)", category: "People" },
  { english: "Neighbor", kannada: "ನೆರೆಯವರು (Nereyavaru)", category: "People" },
  { english: "Guest", kannada: "ಅತಿಥಿ (Atithi)", category: "People" },
  { english: "King", kannada: "ರಾಜ (Raja)", category: "People" },
  { english: "Queen", kannada: "ರಾಣಿ (Rani)", category: "People" },
  { english: "Man", kannada: "ಪುರುಷ (Purusha)", category: "People" },
  { english: "Woman", kannada: "ಮಹಿಳೆ (Mahile)", category: "People" },
  { english: "Boy", kannada: "ಹುಡುಗ (Huduga)", category: "People" },
  { english: "Girl", kannada: "ಹುಡುಗಿ (Hudugi)", category: "People" },
  { english: "Baby", kannada: "ಮಗು (Magu)", category: "People" },
  { english: "People", kannada: "ಜನರು (Janaru)", category: "People" },
];
